package com.pavel.webbet.service;

public enum CommandType {
    LOGIN_COMMAND, LOCALE_COMMAND, NO_SUCH_COMMAND, REGISTER_COMMAND, LOGOUT_COMMAND, DISPLAY_MATCHES_COMMAND,
    ADD_MATCH_COMMAND, CREATE_BET_FORM_COMMAND, ADD_BET_COMMAND, SHOW_MY_BETS_COMMAND, CREATE_MATCH_EDIT_FORM_COMMAND,
    EDIT_MATCH_COMMAND, CREATE_USER_LIST, CREATE_BET_LIST, EDIT_BET_COMMAND, CONFIRM_EDIT_BET_COMMAND
}
